### ISSUE TITLE
[feat] Docker container?

### ISSUE THREAD

**Issue by nwithan8** [Mtillmann/chaptertool#15]
Could you explore making a Docker container of the application that just serves the web UI?

**Comment by Mtillmann** [comment]
Good suggestion I'll look into it soon. Shouldn't be too hard since the app only uses node as a dependency (y)

**Comment by nwithan8** [comment]
Could you also consider releasing a pre-built image to Docker Hub?

**Comment by Mtillmann** [comment]
I'll push it docker later if you need that?

**Comment by Mtillmann** [comment]
```shell
docker run -p 8989:8989 martintillmann/chaptertool-gui
```

this should work

**Comment by nwithan8** [comment]
Awesome, thank you! I've ported this into an Unraid template, so Unraid users can easily install this application on their servers as a Docker container. Just a heads up, in case people start coming in here with issues (hopefully not, this app is awesome and exactly what I'm looking for for a project I'm working on).

**Comment by Mtillmann** [comment]
Great work! Glad to hear that you like it
