### ISSUE TITLE
Add vtt extension to the list of supported files in the file input

### ISSUE THREAD

**Issue by mig8447** [Mtillmann/chaptertool#5]
I attempted to use this on a VTT file, however I had to change the extension to TXT before I could.

**Comment by Mtillmann** [comment]
I assume you used the browser app?

**Comment by mig8447** [comment]
Yes, correct

**Comment by Mtillmann** [comment]
`vtt` and `webvtt` should now be accepted by the file selector

**Comment by mig8447** [comment]
Thanks! I'm guessing the change will take a few hours to be available on github.io, right?

**Comment by Mtillmann** [comment]
no, it should be instant although you might have to force reload the tab

**Comment by mig8447** [comment]
Reloaded without cache, and it is now recognizing the file, but strangely when it is .txt it does recognize the chapters but when it is a .vtt file it doesn't, same file content

**Comment by Mtillmann** [comment]
could you post the file?

**Comment by Mtillmann** [comment]
no, keep the file, it's a mime type issue!

**Comment by Mtillmann** [comment]
@mig8447 can you try again

**Comment by mig8447** [comment]
It is working now! Thank you very much for the quick turnaround

**Comment by Mtillmann** [comment]
thanks for finding the bug!
